preguntas = [[
  "¿Qué es lo que más te gusta de tu trabajo?", # Pronombres interrogativos
  "¿Cuándo fue la última vez que viajaste?",
  "¿Dónde planeas pasar tus vacaciones este año?",
  "¿Quién es tu héroe y por qué?",
  "¿Por qué decidiste estudiar esa carrera?",
  "¿Cómo describirías tu personalidad en tres palabras?",
  "¿Cuánto tiempo dedicas a tus pasatiempos cada semana?",
  "¿Cuál es tu película favorita y por qué?",
  "¿Cuáles son tus metas a corto plazo?",
  "¿A quién admiras más en tu vida?",
  "¿Cuántos hermanos tienes?",
  "¿Qué te motivó a emprender ese proyecto?",
  "¿Cuándo fue la última vez que te sentiste realmente feliz?",
  "¿Dónde te ves en cinco años?",
  "¿Quién te inspira a ser mejor cada día?",
  "¿Por qué elegiste vivir en esa ciudad?",
  "¿Cómo manejas el estrés en tu vida diaria?",
  "¿Cuánto tiempo dedicas al ejercicio cada semana?",
  "¿Cuál es tu libro favorito y por qué?",
  "¿Cuáles son tus habilidades más fuertes en el trabajo?",
  "¿A quién llamarías primero en caso de emergencia?",
  "¿Cuándo fue la última vez que aprendiste algo nuevo?",
  "¿Dónde te gustaría viajar próximamente?",
  "¿Quién te ha influenciado más en tu carrera?",
  "¿Por qué escogiste esa especialización académica?",
  "¿Cómo te relajas después de un día agotador?",
  "¿Cuánto tiempo dedicas a la reflexión diaria?",
  "¿Cuál es tu comida favorita y por qué?",
  "¿Cuáles son tus logros más importantes hasta ahora?",
  "¿A quién le confiarías tu mayor secreto?",
  "¿Cuándo fue la última vez que te sentiste orgulloso de ti mismo?",
  "¿Dónde te gustaría vivir en el futuro?",
  "¿Quién te ha enseñado las lecciones más valiosas en la vida?",
  "¿Por qué decidiste seguir esa profesión?",
  "¿Cómo defines el éxito en tu vida?",
  "¿Cuánto tiempo pasas en las redes sociales cada día?",
  "¿Cuál es tu mayor miedo y por qué?",
  "¿A quién le agradeces más en tu vida?",
  "¿Cuándo fue la última vez que te sorprendiste a ti mismo?",
  "¿Dónde te ves jubilándote eventualmente?",
  "¿Quién es tu modelo a seguir en el ámbito laboral?",
  "¿Por qué crees que es importante mantener metas a largo plazo?",
  "¿Cómo defines la felicidad en tu vida?",
  "¿Cuánto tiempo pasas en actividades creativas cada semana?",
  "¿Cuál es tu mejor consejo para manejar el estrés?",
  "¿A quién admiras más en tu familia?",
  "¿Cuándo fue la última vez que te sentiste completamente relajado?",
  "¿Dónde encuentras inspiración cuando la necesitas?",
  "¿Quién te ha apoyado más en tus decisiones difíciles?",
  "¿Por qué crees que es importante seguir aprendiendo a lo largo de la vida?"
  ],
  ["¿Qué función realiza el módulo 'math' en Python?", # adjetivos interrogativos
    "¿Cuántos elementos tiene la lista 'mi_lista'?",
    "¿Cuál es la diferencia entre una tupla y una lista en Python?",
    "¿Qué tipo de dato representa la variable 'mi_variable'?",
    "¿Cuándo se utiliza la instrucción 'elif' en una estructura condicional?",
    "¿Cuántos parámetros toma la función 'range()' en Python?",
    "¿Qué hace el método 'append()' en una lista?",
    "¿Cuál es el resultado de la expresión '5 ** 3'?",
    "¿Qué significa la sigla 'API' en programación?",
    "¿Cuántas veces se ejecutará este bucle 'for'?",
    "¿Cuál es la diferencia entre '==' y 'is' en Python?",
    "¿Qué es un diccionario en Python?",
    "¿Cuándo se utiliza la palabra clave 'self' en una clase?",
    "¿Cuál es la función de 'pip' en Python?",
    "¿Qué hace la función 'len()' en Python?",
    "¿Qué tipo de bucle es 'while'?",
    "¿Cuántos elementos únicos hay en el conjunto 'mi_conjunto'?",
    "¿Cuál es la diferencia entre 'remove()' y 'discard()' en un conjunto?",
    "¿Qué es una excepción en Python?",
    "¿Cuántos argumentos toma la función 'format()' para formatear una cadena?",
    "¿Cuál es la función de '__init__' en una clase?",
    "¿Qué hace la función 'open()' en Python?",
    "¿Cuál es la diferencia entre 'extend()' y 'append()' en una lista?",
    "¿Cuántos bits representa un byte en Python?",
    "¿Qué significa la palabra clave 'pass' en Python?",
    "¿Cuál es el propósito del método 'pop()' en una lista?",
    "¿Qué es la recursividad en programación?",
    "¿Cuál es la diferencia entre una función y un método en Python?",
    "¿Cuántas veces se ejecuta el código dentro de un bucle 'do-while'?",
    "¿Qué hace la función 'input()' en Python?",
    "¿Cuántos elementos tiene una cadena de texto vacía?",
    "¿Qué significa 'PEP' en la comunidad de Python?",
    "¿Cuál es la función de 'with' en Python?",
    "¿Qué es la comprensión de listas en Python?",
    "¿Cuántos elementos hay en la intersección de dos conjuntos?",
    "¿Cuál es la diferencia entre 'sort()' y 'sorted()' en Python?",
    "¿Qué es la indexación negativa en una lista?",
    "¿Cuál es el resultado de la operación '3 // 2'?",
    "¿Qué hace la función 'strip()' en una cadena de texto?",
    "¿Cuántos argumentos toma la función 'print()' por defecto?",
    "¿Cuál es el propósito de la palabra clave 'global' en Python?",
    "¿Qué significa 'Django' en el contexto de Python?",
    "¿Cuántos elementos puede contener una tupla?",
    "¿Cuál es la diferencia entre una variable local y una variable global?",
    "¿Qué es la herencia en programación orientada a objetos?",
    "¿Cuántos elementos puede tener un diccionario en Python?",
    "¿Cuál es la función de '__main__' en un script de Python?",
    "¿Qué es un generador en Python?",
    "¿Cuál es la diferencia entre 'continue' y 'break' en un bucle?",
    "¿Qué significa la palabra clave 'lambda' en Python?"
    ],

]
