X = ['Donde puedo consultar mi kardex',
 'Donde puedo revisar mi horario',
 'Quien es mi coordinador',
 'Donde tramitar la credencial estudiantil',
 'Que requisitos se requieren para realizar el servicio social',
 'Donde puedo reportar algo que perdi/encontre',
 'Cuales/cuando son las fechas de recuperacion',
 'cuando son vacaciones',
 'Que especialidades existen/hay/o tiene la carrera de XXXX',
 'horario de la biblioteca',
 'donde reviso mis calificaciones',
 'cuando entramos',
 'horario de la cafeteria',
 'horario de las coordinaciones/servicio',
 'horario de la escuela',
 'donde esta el laboratorio X',
 'donde esta posgrado y que posgrados tiene el ITE',
 'Cuales son los costos, o cuanto cuesta un semestre',
 'donde esta enfermeria',
 'como doy de baja una materia',
 'como me cambio de carrera',
 'como o donde cambio la clave de mi correo institucional',
 'como pagar la inscripcion / donde como y porque',
 'que becas hay']

y = ['pronombres_interrogativos',
 'pronombres_interrogativos',
 'pronombres_interrogativos',
 'pronombres_interrogativos',
 'adjetivos_interrogativos',
 'pronombres_interrogativos',
 'pronombres_interrogativos',
 'adverbios_interrogativos',
 'pronombres_interrogativos',
 'particulares_interrogativas',
 'pronombres_interrogativos',
 'adverbios_interrogativos',
 'particulares_interrogativas',
 'particulares_interrogativas',
 'particulares_interrogativas',
 'pronombres_interrogativos',
 'pronombres_interrogativos',
 'pronombres_interrogativos',
 'pronombres_interrogativos',
 'adverbios_interrogativos',
 'adverbios_interrogativos',
 'pronombres_interrogativos',
 'adverbios_interrogativos',
 'adjetivos_interrogativos']